on: push

name: "Deploy Ions"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'corretto'
          java-version: '8'
      - uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 'latest'
      - run: clojure -e "(+ 1 1)"
