on: push

name: "Deploy Ions"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::118776085668:role/github-actions-ions-deployment
          aws-region: eu-central-1
      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 'latest'
      - name: Setup borkdude/jet
        run: bash <(curl -s https://raw.githubusercontent.com/borkdude/jet/master/install)
      - name: Cache Clojure Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - name: Push code to AWS CodeDeploy
        run: push_result=$(clojure -A:ion-dev '{:op :push}')
      - name: Display push result
        run: echo "$push_result"
